FROM --platform=$TARGETOS/$TARGETARCH node:17-bullseye-slim

LABEL       author="Jesper Richert" maintainer="hey@jespersen.zip"

RUN         apt update \
    && apt -y install ffmpeg iproute2 git libsqlite3-dev python3 python3-dev ca-certificates dnsutils tzdata zip tar curl build-essential libtool \
    && npm -g install npm@8.11.0 \
    && useradd -m -d /home/container container

USER        container
ENV         USER=container HOME=/home/container
WORKDIR     /home/container

COPY        entrypoint.sh /entrypoint.sh
CMD         [ "/bin/bash", "/entrypoint.sh" ]
